Update content-type.txt
danielmiessler/SecLists pull request #656
Opened 2021-09-24 23:51 UTC by A1vinSmith

2021-11-24 09:54 UTC, g0tmi1k commented
Source?

2021-11-24 23:53 UTC, A1vinSmith commented
Not sure why. But something like this https://cweiske.de/tagebuch/php-mimetype.htm

2021-12-04 16:34 UTC, Sandesh333333 requested changes

2021-12-04 16:34 UTC, Sandesh333333 commented on Miscellaneous/web/content-type.txt
>  video/3gpp2
Download

2021-12-04 19:09 UTC, A1vinSmith commented on Miscellaneous/web/content-type.txt
>  video/3gpp2
sorry what do you mean by that? Adding a comment for the line?

2021-12-05 14:53 UTC, PinkDev1 approved these changes

2022-02-02 23:40 UTC, g0tmi1k commented
Like to try and give credit where possible. also helps people to understand more/

2022-02-02 23:40 UTC, merged

2022-02-02 23:40 UTC, g0tmi1k commented
Thank you!

2022-04-12 14:15 UTC, Sandesh333333 approved these changes