update site to download password lists
danielmiessler/SecLists pull request #775
Opened 2022-06-23 12:42 UTC by noraj

The previous Gist link was dead, adding weakpass instead

2022-06-23 19:14 UTC, ItsIgnacioPortal requested changes
weakpass is a fine addition. But the gist still exists on the Internet Archive.

```
wordlist created from original 41G stash via:

grep -rohP '(?<=:).*$' | uniq > breachcompilation.txt

Then, compressed with:

7z a breachcompilation.txt.7z breachcompilation.txt

Size:

4.1G compressed
9.0G uncompressed

No personal information included - just a list of passwords.

magnet url:

magnet:?xt=urn:btih:5a9ba318a5478769ddc7393f1e4ac928d9aa4a71&dn=breachcompilation.txt.7z
```

Please add this link:

https://web.archive.org/web/20200501154512/https://gist.github.com/scottlinux/9a3b11257ac575e4f71de811322ce6b3

2022-06-25 10:53 UTC, ItsIgnacioPortal approved these changes

2022-07-25 01:37 UTC, ItsIgnacioPortal commented
This fixes #758

2022-08-02 05:34 UTC, merged

2022-08-02 05:35 UTC, g0tmi1k commented
Good job guys!